name: Build and Scan with Trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TRIVY_VERSION: 0.52.0

jobs:
  build_and_scan:
    name: Build, Scan and report
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install trivy 
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}
          trivy --version

      - name: Run trivy scan
        run: |
          trivy image --show-suppressed --vex ./openvex.json docker.redpanda.com/redpandadata/console:v2.8.5

      - name: Run Diagnostic Trivy Scan in JSON format
        run: |
          trivy image \
            --format json \
            docker.redpanda.com/redpandadata/console:v2.8.5

      #- name: Upload Trivy scan results to GitHub Security tab
      #  if (indsæt ":" her) always()
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: 'trivy-results.sarif'

# Change